# Base configs
baseurl: ""
url: "http://mjsundar.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-46465113-2"

# UI configs
title: "Vibrant photography"
subtitle: "See the world with different way...!"
author: "Manoj Sundar"
bio: "I am a Photographer in a simple way. Lets show the objects with unbelivable Dimensions with some Enginneering Skills :)"
publicise: "see my code @ github"
web_design: "Sriram_SDS"
social_urls:
  facebook: "https://www.facebook.com/manojsundar98"
  instagram: "https://www.instagram.com/manoj_sundar"
  github: "https://www.github.com/mjsundar"
  
